name

diff --git a/.github/workflows/publish_macos.yml b/.github/workflows/publish_macos.yml
--- a/.github/workflows/publish_macos.yml
+++ b/.github/workflows/publish_macos.yml
@@ -78,14 +78,33 @@ jobs:
       working-directory: ${{github.workspace}}/tidy-mac-installer
       shell: bash
       run: |
-        security create-keychain -p password1234 build.keychain 
+        echo "Deleting existing keychain (if any)..."
+        security delete-keychain build.keychain || true
+        
+        echo "Creating keychain..."
+        security create-keychain -p password1234 build.keychain || { echo "Failed to create keychain"; exit 1; }
+        
+        echo "Setting default keychain..."
         security default-keychain -s build.keychain
+        
+        echo "Unlocking keychain..."
         security unlock-keychain -p password1234 build.keychain
-        echo "${APPLE_DEVELOPER_ID_INSTALLER}" | base64 --decode > "certificate.p12"
-        security import "certificate.p12" -k build.keychain -P ${APPLE_DEVELOPER_ID_INSTALLER_PW} -T /usr/bin/codesign -T /usr/bin/productsign
-        echo "${APPLE_DEVELOPER_ID_APPLICATION}" | base64 --decode > "certificate.p12"
-        security import "certificate.p12" -k build.keychain -P ${APPLE_DEVELOPER_ID_APPLICATION_PW} -T /usr/bin/codesign -T /usr/bin/productsign
+        
+        echo "Decoding installer certificate..."
+        echo "${APPLE_DEVELOPER_ID_INSTALLER}" | base64 --decode > installer_certificate.p12
+        
+        echo "Decoding application certificate..."
+        echo "${APPLE_DEVELOPER_ID_APPLICATION}" | base64 --decode > application_certificate.p12
+        
+        echo "Importing installer certificate..."
+        security import installer_certificate.p12 -k build.keychain -P ${APPLE_DEVELOPER_ID_INSTALLER_PW} -T /usr/bin/codesign -T /usr/bin/productsign || { echo "Failed to import installer certificate"; exit 1; }
+        
+        echo "Importing application certificate..."
+        security import application_certificate.p12 -k build.keychain -P ${APPLE_DEVELOPER_ID_APPLICATION_PW} -T /usr/bin/codesign -T /usr/bin/productsign || { echo "Failed to import application certificate"; exit 1; }
+        
+        echo "Setting keychain partition list..."
         security set-key-partition-list -S apple-tool:,apple:,codesign:,productsign: -s -k password1234 build.keychain
+
 
 
     ############################################################
